
pipeline {

	agent { label 'AWS' }

	environment {
        GITHUB_TOKEN = credentials('Github-Token')
    }

	stages {
		stage ('Build Docker Containers') {
			steps {
				// make sure there aren't any already existing containers
            	sh 'docker compose --project-directory jenkins/integration_tests rm -f'
            	sh 'docker compose --project-directory jenkins/integration_tests pull'
            	sh 'docker compose --project-directory jenkins/integration_tests up --force-recreate --build --wait'
            	// wait for the script to install wordpress
            	// TODO: remove the sleep and implement polling until the container is stopped?
            	sh "sleep 60"
			}
		}

		stage ('Create PHP Container') {
			steps {
				script {
					// have to do this instead of using a docker agent as it needs to run on the same agent
					// using a docker agent in this step seems to use another agent completly rather than
					// a docker container within the pipeline agent
					dockerImageId = sh(returnStdout: true, script: 'docker build -f jenkins/dockerfile . -q').trim()
					dockerContainerId = sh(returnStdout: true, script: "docker container run -d --network=host ${dockerImageId} tail -f /dev/null").trim()
				}
			}
		}

		stage ('Install Vendor') {
			steps {
	            // no-cache because the container fails to create directories when cloning
	            // from git eg:
	            // could not create leading directories of 
	            // '/.composer/cache/vcs/https ---github.com-bovigo-vfsStream.git'
				sh "docker exec ${dockerContainerId} /bin/sh -c 'cd /usr/src/odoo_conn; composer install --no-cache'"
			}
		}

        stage ('Endpoint Tests') {
            steps {
                sh "docker exec ${dockerContainerId} /bin/sh -c 'cd /usr/src/odoo_conn; vendor/bin/phpunit jenkins/integration_tests/tests/endpoint_tests'"
            }
        }
	}

	post { 
        always {
        	sh 'docker compose --project-directory jenkins/integration_tests down'
        	sh 'docker compose --project-directory jenkins/integration_tests rm -f'
            sh "docker container rm --force ${dockerContainerId}"
            sh "curl \
                -X POST \
                -H \"Accept: application/vnd.github+json\" \
                -H \"Authorization: Bearer $GITHUB_TOKEN\" \
                https://api.github.com/repos/jack-dane/odoo-wp-plugin/statuses/$GIT_COMMIT \
                -d \'{\"state\":\"${currentBuild.result.toLowerCase()}\",\"context\":\"Jenkins Integration Tests\"}\'"
        }
    }

}