
pipeline {
    
    agent { 
        dockerfile {
            filename '../dockerfile'
            dir 'jenkins/php_tests'
            args '-it --entrypoint='
        }
    }
    
    environment {
        GITHUB_TOKEN = credentials('Github-Token')
    }

    stages {
        stage ('Install Vendor') {
            steps {
                sh 'cd $WORKSPACE'
                // no-cache because the container fails to create directories when cloning
                // from git eg:
                // could not create leading directories of 
                // '/.composer/cache/vcs/https ---github.com-bovigo-vfsStream.git'
                sh 'composer install --no-cache'
            }
        }

        stage ('Test') {
            steps {
                sh 'vendor/bin/phpunit tests'
            }
        }
    }

    post { 
        always {
            // send the reslt to GitHub
            sh "curl \
                -X POST \
                -H \"Accept: application/vnd.github+json\" \
                -H \"Authorization: Bearer $GITHUB_TOKEN\" \
                https://api.github.com/repos/jack-dane/odoo-wp-plugin/statuses/$GIT_COMMIT \
                -d \'{\"state\":\"${currentBuild.result.toLowerCase()}\",\"context\":\"Jenkins Unit Tests\"}\'"
        }
    }

}
